build:
  image: golang:1.5
  environment:
    - CGO_ENABLED=0
  commands:
    - make deps
    - make vet
    - make build
    - make test

publish:
  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: riteam/drone-azure-storage
    tag: latest
    when:
      branch: master
  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: riteam/drone-azure-storage
    tag: develop
    when:
      branch: develop
